///************************************************
/// Generated by: HaiHD
/// Date: 14/08/2015 01:45:45
/// Goal: Create User Service Class for V_DM_HOC_SINH2
///************************************************
/// <summary>
/// Create User Service Class for V_DM_HOC_SINH2
/// </summary>

using System;
using BKI_QLTTQuocAnh.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_QLTTQuocAnh.US{

public class US_V_DM_HOC_SINH2 : US_Object
{
	private const string c_TableName = "V_DM_HOC_SINH2";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strMA_DOI_TUONG 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_DOI_TUONG", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_DOI_TUONG"] = value;
		}
	}

	public bool IsMA_DOI_TUONGNull() 
	{
		return pm_objDR.IsNull("MA_DOI_TUONG");
	}

	public void SetMA_DOI_TUONGNull() {
		pm_objDR["MA_DOI_TUONG"] = System.Convert.DBNull;
	}

	public string strHO 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "HO", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["HO"] = value;
		}
	}

	public bool IsHONull() 
	{
		return pm_objDR.IsNull("HO");
	}

	public void SetHONull() {
		pm_objDR["HO"] = System.Convert.DBNull;
	}

	public string strTEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN"] = value;
		}
	}

	public bool IsTENNull() 
	{
		return pm_objDR.IsNull("TEN");
	}

	public void SetTENNull() {
		pm_objDR["TEN"] = System.Convert.DBNull;
	}

	public string strHO_TEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "HO_TEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["HO_TEN"] = value;
		}
	}

	public bool IsHO_TENNull() 
	{
		return pm_objDR.IsNull("HO_TEN");
	}

	public void SetHO_TENNull() {
		pm_objDR["HO_TEN"] = System.Convert.DBNull;
	}

	public string strTRUONG_DANG_HOC 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TRUONG_DANG_HOC", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TRUONG_DANG_HOC"] = value;
		}
	}

	public bool IsTRUONG_DANG_HOCNull() 
	{
		return pm_objDR.IsNull("TRUONG_DANG_HOC");
	}

	public void SetTRUONG_DANG_HOCNull() {
		pm_objDR["TRUONG_DANG_HOC"] = System.Convert.DBNull;
	}

	public string strEMAIL_HS 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "EMAIL_HS", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["EMAIL_HS"] = value;
		}
	}

	public bool IsEMAIL_HSNull() 
	{
		return pm_objDR.IsNull("EMAIL_HS");
	}

	public void SetEMAIL_HSNull() {
		pm_objDR["EMAIL_HS"] = System.Convert.DBNull;
	}

	public string strEMAIL_PH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "EMAIL_PH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["EMAIL_PH"] = value;
		}
	}

	public bool IsEMAIL_PHNull() 
	{
		return pm_objDR.IsNull("EMAIL_PH");
	}

	public void SetEMAIL_PHNull() {
		pm_objDR["EMAIL_PH"] = System.Convert.DBNull;
	}

	public string strDIA_CHI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DIA_CHI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DIA_CHI"] = value;
		}
	}

	public bool IsDIA_CHINull() 
	{
		return pm_objDR.IsNull("DIA_CHI");
	}

	public void SetDIA_CHINull() {
		pm_objDR["DIA_CHI"] = System.Convert.DBNull;
	}

	public string strSDT_HS 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "SDT_HS", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["SDT_HS"] = value;
		}
	}

	public bool IsSDT_HSNull() 
	{
		return pm_objDR.IsNull("SDT_HS");
	}

	public void SetSDT_HSNull() {
		pm_objDR["SDT_HS"] = System.Convert.DBNull;
	}

	public string strSDT_PH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "SDT_PH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["SDT_PH"] = value;
		}
	}

	public bool IsSDT_PHNull() 
	{
		return pm_objDR.IsNull("SDT_PH");
	}

	public void SetSDT_PHNull() {
		pm_objDR["SDT_PH"] = System.Convert.DBNull;
	}

	public string strHO_TEN_PH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "HO_TEN_PH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["HO_TEN_PH"] = value;
		}
	}

	public bool IsHO_TEN_PHNull() 
	{
		return pm_objDR.IsNull("HO_TEN_PH");
	}

	public void SetHO_TEN_PHNull() {
		pm_objDR["HO_TEN_PH"] = System.Convert.DBNull;
	}

	public string strSDT_CO_DINH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "SDT_CO_DINH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["SDT_CO_DINH"] = value;
		}
	}

	public bool IsSDT_CO_DINHNull() 
	{
		return pm_objDR.IsNull("SDT_CO_DINH");
	}

	public void SetSDT_CO_DINHNull() {
		pm_objDR["SDT_CO_DINH"] = System.Convert.DBNull;
	}

	public string strFACEBOOK 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "FACEBOOK", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["FACEBOOK"] = value;
		}
	}

	public bool IsFACEBOOKNull() 
	{
		return pm_objDR.IsNull("FACEBOOK");
	}

	public void SetFACEBOOKNull() {
		pm_objDR["FACEBOOK"] = System.Convert.DBNull;
	}

	public string strSKYPE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "SKYPE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["SKYPE"] = value;
		}
	}

	public bool IsSKYPENull() 
	{
		return pm_objDR.IsNull("SKYPE");
	}

	public void SetSKYPENull() {
		pm_objDR["SKYPE"] = System.Convert.DBNull;
	}

	public string strDELETE_HS_YN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DELETE_HS_YN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DELETE_HS_YN"] = value;
		}
	}

	public bool IsDELETE_HS_YNNull() 
	{
		return pm_objDR.IsNull("DELETE_HS_YN");
	}

	public void SetDELETE_HS_YNNull() {
		pm_objDR["DELETE_HS_YN"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_SINH
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_SINH", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_SINH"] = value;
		}
	}

	public bool IsNGAY_SINHNull()
	{
		return pm_objDR.IsNull("NGAY_SINH");
	}

	public void SetNGAY_SINHNull()
	{
		pm_objDR["NGAY_SINH"] = System.Convert.DBNull;
	}

	public string strTRANG_THAI_GD_HOC 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TRANG_THAI_GD_HOC", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TRANG_THAI_GD_HOC"] = value;
		}
	}

	public bool IsTRANG_THAI_GD_HOCNull() 
	{
		return pm_objDR.IsNull("TRANG_THAI_GD_HOC");
	}

	public void SetTRANG_THAI_GD_HOCNull() {
		pm_objDR["TRANG_THAI_GD_HOC"] = System.Convert.DBNull;
	}

	public decimal dcID_LOP_MON 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_LOP_MON", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_LOP_MON"] = value;
		}
	}

	public bool IsID_LOP_MONNull()	{
		return pm_objDR.IsNull("ID_LOP_MON");
	}

	public void SetID_LOP_MONNull() {
		pm_objDR["ID_LOP_MON"] = System.Convert.DBNull;
	}

	public string strMA_LOP_MON 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_LOP_MON", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_LOP_MON"] = value;
		}
	}

	public bool IsMA_LOP_MONNull() 
	{
		return pm_objDR.IsNull("MA_LOP_MON");
	}

	public void SetMA_LOP_MONNull() {
		pm_objDR["MA_LOP_MON"] = System.Convert.DBNull;
	}

	public string strTEN_LOP_MON 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_LOP_MON", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_LOP_MON"] = value;
		}
	}

	public bool IsTEN_LOP_MONNull() 
	{
		return pm_objDR.IsNull("TEN_LOP_MON");
	}

	public void SetTEN_LOP_MONNull() {
		pm_objDR["TEN_LOP_MON"] = System.Convert.DBNull;
	}

	public decimal dcDON_GIA_BUOI_HOC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "DON_GIA_BUOI_HOC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["DON_GIA_BUOI_HOC"] = value;
		}
	}

	public bool IsDON_GIA_BUOI_HOCNull()	{
		return pm_objDR.IsNull("DON_GIA_BUOI_HOC");
	}

	public void SetDON_GIA_BUOI_HOCNull() {
		pm_objDR["DON_GIA_BUOI_HOC"] = System.Convert.DBNull;
	}

	public decimal dcTRANG_THAI_LOP_MON 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "TRANG_THAI_LOP_MON", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["TRANG_THAI_LOP_MON"] = value;
		}
	}

	public bool IsTRANG_THAI_LOP_MONNull()	{
		return pm_objDR.IsNull("TRANG_THAI_LOP_MON");
	}

	public void SetTRANG_THAI_LOP_MONNull() {
		pm_objDR["TRANG_THAI_LOP_MON"] = System.Convert.DBNull;
	}

	public DateTime datTHOI_GIAN_HOC_FROM_DATE
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "THOI_GIAN_HOC_FROM_DATE", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["THOI_GIAN_HOC_FROM_DATE"] = value;
		}
	}

	public bool IsTHOI_GIAN_HOC_FROM_DATENull()
	{
		return pm_objDR.IsNull("THOI_GIAN_HOC_FROM_DATE");
	}

	public void SetTHOI_GIAN_HOC_FROM_DATENull()
	{
		pm_objDR["THOI_GIAN_HOC_FROM_DATE"] = System.Convert.DBNull;
	}

	public DateTime datTHOI_GIAN_HOC_TO_DATE
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "THOI_GIAN_HOC_TO_DATE", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["THOI_GIAN_HOC_TO_DATE"] = value;
		}
	}

	public bool IsTHOI_GIAN_HOC_TO_DATENull()
	{
		return pm_objDR.IsNull("THOI_GIAN_HOC_TO_DATE");
	}

	public void SetTHOI_GIAN_HOC_TO_DATENull()
	{
		pm_objDR["THOI_GIAN_HOC_TO_DATE"] = System.Convert.DBNull;
	}

	public DateTime datMOT_NAM_SAU_NGAY_KET_THUC
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "MOT_NAM_SAU_NGAY_KET_THUC", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["MOT_NAM_SAU_NGAY_KET_THUC"] = value;
		}
	}

	public bool IsMOT_NAM_SAU_NGAY_KET_THUCNull()
	{
		return pm_objDR.IsNull("MOT_NAM_SAU_NGAY_KET_THUC");
	}

	public void SetMOT_NAM_SAU_NGAY_KET_THUCNull()
	{
		pm_objDR["MOT_NAM_SAU_NGAY_KET_THUC"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_V_DM_HOC_SINH2() 
	{
		pm_objDS = new DS_V_DM_HOC_SINH2();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_DM_HOC_SINH2(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_DM_HOC_SINH2(decimal i_dbID) 
	{
		pm_objDS = new DS_V_DM_HOC_SINH2();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
