///************************************************
/// Generated by: Vupl
/// Date: 17/05/2015 11:33:02
/// Goal: Create Form for V_DM_HOC_SINH_GD_HOC_DM_LOP_MON
///************************************************


using System;
using System.Data;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

using IP.Core.IPCommon;
using IP.Core.IPException;
using IP.Core.IPData;
using IP.Core.IPUserService;
using IP.Core.IPSystemAdmin;

using BKI_QLTTQuocAnh.US;
using BKI_QLTTQuocAnh.DS;
using BKI_QLTTQuocAnh.DS.CDBNames;
using BKI_QLTTQuocAnh.DanhMuc;

using C1.Win.C1FlexGrid;

namespace BKI_QLTTQuocAnh {



    public class f250_dm_hs_theo_lop : System.Windows.Forms.Form {
        internal System.Windows.Forms.ImageList ImageList;
        internal System.Windows.Forms.Panel m_pnl_out_place_dm;
        private C1.Win.C1FlexGrid.C1FlexGrid m_fg;
        internal SIS.Controls.Button.SiSButton m_cmd_exit;
        internal SIS.Controls.Button.SiSButton m_cmd_view;
        private Label m_lbl_header;
        private Panel panel1;
        private ComboBox m_cbo_trang_thai_hv;
        private Label m_lbl_trang_thai_hv;
        private TextBox m_txt_search;
        private Label m_lbl_search;
        private ComboBox m_cbo_lop_mon;
        internal SIS.Controls.Button.SiSButton m_cmd_search;
        private Label m_lbl_lop_mon;
        internal SIS.Controls.Button.SiSButton m_cmd_delete;
        internal SIS.Controls.Button.SiSButton m_cmd_update;
        internal SIS.Controls.Button.SiSButton m_cmd_insert;
        private System.ComponentModel.IContainer components;

        public f250_dm_hs_theo_lop()
        {
            //
            // Required for Windows Form Designer support
            //
            InitializeComponent();

            //
            // TODO: Add any constructor code after InitializeComponent call
            //
            format_controls();
        }

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code
        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(f250_dm_hs_theo_lop));
            this.ImageList = new System.Windows.Forms.ImageList(this.components);
            this.m_pnl_out_place_dm = new System.Windows.Forms.Panel();
            this.m_cmd_view = new SIS.Controls.Button.SiSButton();
            this.m_cmd_exit = new SIS.Controls.Button.SiSButton();
            this.m_fg = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.m_lbl_header = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.m_cbo_trang_thai_hv = new System.Windows.Forms.ComboBox();
            this.m_lbl_trang_thai_hv = new System.Windows.Forms.Label();
            this.m_txt_search = new System.Windows.Forms.TextBox();
            this.m_lbl_search = new System.Windows.Forms.Label();
            this.m_cbo_lop_mon = new System.Windows.Forms.ComboBox();
            this.m_cmd_search = new SIS.Controls.Button.SiSButton();
            this.m_lbl_lop_mon = new System.Windows.Forms.Label();
            this.m_cmd_insert = new SIS.Controls.Button.SiSButton();
            this.m_cmd_update = new SIS.Controls.Button.SiSButton();
            this.m_cmd_delete = new SIS.Controls.Button.SiSButton();
            this.m_pnl_out_place_dm.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).BeginInit();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // ImageList
            // 
            this.ImageList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("ImageList.ImageStream")));
            this.ImageList.TransparentColor = System.Drawing.Color.Transparent;
            this.ImageList.Images.SetKeyName(0, "");
            this.ImageList.Images.SetKeyName(1, "");
            this.ImageList.Images.SetKeyName(2, "");
            this.ImageList.Images.SetKeyName(3, "");
            this.ImageList.Images.SetKeyName(4, "");
            this.ImageList.Images.SetKeyName(5, "");
            this.ImageList.Images.SetKeyName(6, "");
            this.ImageList.Images.SetKeyName(7, "");
            this.ImageList.Images.SetKeyName(8, "");
            this.ImageList.Images.SetKeyName(9, "");
            this.ImageList.Images.SetKeyName(10, "");
            this.ImageList.Images.SetKeyName(11, "");
            this.ImageList.Images.SetKeyName(12, "");
            this.ImageList.Images.SetKeyName(13, "");
            this.ImageList.Images.SetKeyName(14, "");
            this.ImageList.Images.SetKeyName(15, "");
            this.ImageList.Images.SetKeyName(16, "");
            this.ImageList.Images.SetKeyName(17, "");
            this.ImageList.Images.SetKeyName(18, "");
            this.ImageList.Images.SetKeyName(19, "");
            this.ImageList.Images.SetKeyName(20, "");
            this.ImageList.Images.SetKeyName(21, "");
            // 
            // m_pnl_out_place_dm
            // 
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_delete);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_update);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_insert);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_view);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_exit);
            this.m_pnl_out_place_dm.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.m_pnl_out_place_dm.Location = new System.Drawing.Point(0, 373);
            this.m_pnl_out_place_dm.Name = "m_pnl_out_place_dm";
            this.m_pnl_out_place_dm.Padding = new System.Windows.Forms.Padding(4);
            this.m_pnl_out_place_dm.Size = new System.Drawing.Size(686, 36);
            this.m_pnl_out_place_dm.TabIndex = 19;
            // 
            // m_cmd_view
            // 
            this.m_cmd_view.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_view.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_view.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_view.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_view.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_view.ImageIndex = 18;
            this.m_cmd_view.ImageList = this.ImageList;
            this.m_cmd_view.Location = new System.Drawing.Point(92, 4);
            this.m_cmd_view.Name = "m_cmd_view";
            this.m_cmd_view.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_view.TabIndex = 21;
            this.m_cmd_view.Text = "Xem";
            // 
            // m_cmd_exit
            // 
            this.m_cmd_exit.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_exit.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_exit.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_exit.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_exit.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_exit.ImageIndex = 12;
            this.m_cmd_exit.ImageList = this.ImageList;
            this.m_cmd_exit.Location = new System.Drawing.Point(4, 4);
            this.m_cmd_exit.Name = "m_cmd_exit";
            this.m_cmd_exit.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_exit.TabIndex = 11;
            this.m_cmd_exit.Text = "Thoát (Esc)";
            this.m_cmd_exit.Visible = false;
            // 
            // m_fg
            // 
            this.m_fg.ColumnInfo = resources.GetString("m_fg.ColumnInfo");
            this.m_fg.Dock = System.Windows.Forms.DockStyle.Fill;
            this.m_fg.Location = new System.Drawing.Point(0, 169);
            this.m_fg.Name = "m_fg";
            this.m_fg.Size = new System.Drawing.Size(686, 204);
            this.m_fg.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("m_fg.Styles"));
            this.m_fg.TabIndex = 20;
            // 
            // m_lbl_header
            // 
            this.m_lbl_header.Dock = System.Windows.Forms.DockStyle.Top;
            this.m_lbl_header.Font = new System.Drawing.Font("Microsoft Sans Serif", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.m_lbl_header.ForeColor = System.Drawing.Color.Maroon;
            this.m_lbl_header.Location = new System.Drawing.Point(0, 0);
            this.m_lbl_header.Name = "m_lbl_header";
            this.m_lbl_header.Size = new System.Drawing.Size(686, 45);
            this.m_lbl_header.TabIndex = 21;
            this.m_lbl_header.Text = "DANH SÁCH HỌC SINH THEO LỚP MÔN";
            this.m_lbl_header.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.m_cbo_trang_thai_hv);
            this.panel1.Controls.Add(this.m_lbl_trang_thai_hv);
            this.panel1.Controls.Add(this.m_txt_search);
            this.panel1.Controls.Add(this.m_lbl_search);
            this.panel1.Controls.Add(this.m_cbo_lop_mon);
            this.panel1.Controls.Add(this.m_cmd_search);
            this.panel1.Controls.Add(this.m_lbl_lop_mon);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 45);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(686, 124);
            this.panel1.TabIndex = 22;
            // 
            // m_cbo_trang_thai_hv
            // 
            this.m_cbo_trang_thai_hv.FormattingEnabled = true;
            this.m_cbo_trang_thai_hv.Location = new System.Drawing.Point(129, 34);
            this.m_cbo_trang_thai_hv.Name = "m_cbo_trang_thai_hv";
            this.m_cbo_trang_thai_hv.Size = new System.Drawing.Size(176, 21);
            this.m_cbo_trang_thai_hv.TabIndex = 6;
            this.m_cbo_trang_thai_hv.Visible = false;
            // 
            // m_lbl_trang_thai_hv
            // 
            this.m_lbl_trang_thai_hv.AutoSize = true;
            this.m_lbl_trang_thai_hv.Location = new System.Drawing.Point(7, 37);
            this.m_lbl_trang_thai_hv.Name = "m_lbl_trang_thai_hv";
            this.m_lbl_trang_thai_hv.Size = new System.Drawing.Size(58, 13);
            this.m_lbl_trang_thai_hv.TabIndex = 5;
            this.m_lbl_trang_thai_hv.Text = "Trạng thái ";
            this.m_lbl_trang_thai_hv.Visible = false;
            // 
            // m_txt_search
            // 
            this.m_txt_search.Location = new System.Drawing.Point(129, 59);
            this.m_txt_search.Name = "m_txt_search";
            this.m_txt_search.Size = new System.Drawing.Size(260, 20);
            this.m_txt_search.TabIndex = 3;
            // 
            // m_lbl_search
            // 
            this.m_lbl_search.AutoSize = true;
            this.m_lbl_search.Location = new System.Drawing.Point(7, 62);
            this.m_lbl_search.Name = "m_lbl_search";
            this.m_lbl_search.Size = new System.Drawing.Size(49, 13);
            this.m_lbl_search.TabIndex = 2;
            this.m_lbl_search.Text = "Tìm kiếm";
            // 
            // m_cbo_lop_mon
            // 
            this.m_cbo_lop_mon.FormattingEnabled = true;
            this.m_cbo_lop_mon.Location = new System.Drawing.Point(129, 9);
            this.m_cbo_lop_mon.Name = "m_cbo_lop_mon";
            this.m_cbo_lop_mon.Size = new System.Drawing.Size(121, 21);
            this.m_cbo_lop_mon.TabIndex = 1;
            // 
            // m_cmd_search
            // 
            this.m_cmd_search.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_search.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_search.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_search.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_search.ImageIndex = 5;
            this.m_cmd_search.ImageList = this.ImageList;
            this.m_cmd_search.Location = new System.Drawing.Point(414, 54);
            this.m_cmd_search.Name = "m_cmd_search";
            this.m_cmd_search.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_search.TabIndex = 4;
            this.m_cmd_search.Text = "Lọc dữ liệu";
            // 
            // m_lbl_lop_mon
            // 
            this.m_lbl_lop_mon.AutoSize = true;
            this.m_lbl_lop_mon.Location = new System.Drawing.Point(7, 12);
            this.m_lbl_lop_mon.Name = "m_lbl_lop_mon";
            this.m_lbl_lop_mon.Size = new System.Drawing.Size(48, 13);
            this.m_lbl_lop_mon.TabIndex = 0;
            this.m_lbl_lop_mon.Text = "Lớp môn";
            // 
            // m_cmd_insert
            // 
            this.m_cmd_insert.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_insert.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_insert.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_insert.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_insert.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_insert.ImageIndex = 2;
            this.m_cmd_insert.ImageList = this.ImageList;
            this.m_cmd_insert.Location = new System.Drawing.Point(180, 4);
            this.m_cmd_insert.Name = "m_cmd_insert";
            this.m_cmd_insert.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_insert.TabIndex = 22;
            this.m_cmd_insert.Text = "&Thêm";
            // 
            // m_cmd_update
            // 
            this.m_cmd_update.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_update.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_update.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_update.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_update.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_update.ImageIndex = 3;
            this.m_cmd_update.ImageList = this.ImageList;
            this.m_cmd_update.Location = new System.Drawing.Point(268, 4);
            this.m_cmd_update.Name = "m_cmd_update";
            this.m_cmd_update.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_update.TabIndex = 23;
            this.m_cmd_update.Text = "&Sửa";
            // 
            // m_cmd_delete
            // 
            this.m_cmd_delete.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_delete.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_delete.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_delete.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_delete.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_delete.ImageIndex = 4;
            this.m_cmd_delete.ImageList = this.ImageList;
            this.m_cmd_delete.Location = new System.Drawing.Point(356, 4);
            this.m_cmd_delete.Name = "m_cmd_delete";
            this.m_cmd_delete.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_delete.TabIndex = 24;
            this.m_cmd_delete.Text = "&Xoá";
            // 
            // f250_dm_hs_theo_lop
            // 
            this.AutoScaleBaseSize = new System.Drawing.Size(5, 13);
            this.ClientSize = new System.Drawing.Size(686, 409);
            this.Controls.Add(this.m_fg);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.m_lbl_header);
            this.Controls.Add(this.m_pnl_out_place_dm);
            this.Name = "f250_dm_hs_theo_lop";
            this.Text = "F250 - DANH SÁCH HỌC VIÊN THEO LỚP MÔN";
            this.Load += new System.EventHandler(this.f250_dm_hs_theo_lop_Load);
            this.m_pnl_out_place_dm.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).EndInit();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.ResumeLayout(false);

        }
        #endregion

        #region Public Interface
        public void display()
        {
            this.ShowDialog();
        }
        #endregion

        #region Data Structure
        private enum e_col_Number {
            DIA_CHI = 9
,
            DON_GIA_BUOI_HOC = 16
                ,
            MA_DOI_TUONG = 1
                ,
            TONG_SO_BUOI_HOC = 18
                ,
            DELETE_YN = 12
                ,
            EMAIL_HS = 8
                ,
            TEN_LOP_MON = 15
                ,
            TEN = 5
                ,
            TONG_TIEN_KHOA_HOC = 22
                ,
            MA_LOP_MON = 14
                ,
            HO_TEN = 6
                ,
            TRANG_THAI_LOP_MON = 17
                ,
            TEN_LOAI_DOI_TUONG = 3
                ,
            THOI_GIAN_HOC_TO_DATE = 20
                ,
            THOI_GIAN_HOC_FROM_DATE = 19
                ,
            ID_LOAI_DOI_TUONG = 2
                ,
            TRANG_THAI_YN = 24
                ,
            ID_LOP_MON = 13
                ,
            TRUONG_DANG_HOC = 7
                ,
            HO = 4
                ,
            SDT_HS = 10
                ,
            NGAY_SINH = 11
                ,
            ID_GD_HOC = 23
                , GHI_CHU = 21

        }
        #endregion

        #region Members
        ITransferDataRow m_obj_trans;
        DS_V_DM_HOC_SINH_GD_HOC_DM_LOP_MON m_ds = new DS_V_DM_HOC_SINH_GD_HOC_DM_LOP_MON();
        US_V_DM_HOC_SINH_GD_HOC_DM_LOP_MON m_us = new US_V_DM_HOC_SINH_GD_HOC_DM_LOP_MON();
        #endregion

        #region Private Methods
        private void format_controls()
        {
            CControlFormat.setFormStyle(this, new CAppContext_201());
            this.m_lbl_header.Font = new System.Drawing.Font("Microsoft Sans Serif", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            CControlFormat.setC1FlexFormat(m_fg);
            CGridUtils.AddSave_Excel_Handlers(m_fg);
            CGridUtils.AddSearch_Handlers(m_fg);
            set_define_events();
            this.KeyPreview = true;
        }
        private void set_initial_form_load()
        {
            //CCommon.load_data_2_cbo_lop_mon(-1, m_cbo_lop_mon);


            add_value_to_cbo_lop();

            m_obj_trans = get_trans_object(m_fg);
            //m_cbo_lop_mon.SelectedIndexChanged += m_cbo_lop_mon_SelectedIndexChanged;
            load_data_2_grid();
        }

        private void add_value_to_cbo_lop()
        {
            DS_DM_LOP_MON v_ds = new DS_DM_LOP_MON();
            US_DM_LOP_MON v_us = new US_DM_LOP_MON();
            v_us.FillDataset(v_ds,"where TRANG_THAI_LOP_MON = 88");

            m_cbo_lop_mon.DataSource = v_ds.DM_LOP_MON;
            m_cbo_lop_mon.DisplayMember = DM_LOP_MON.MO_TA;
            m_cbo_lop_mon.ValueMember = DM_LOP_MON.ID;
        }
        private ITransferDataRow get_trans_object(C1.Win.C1FlexGrid.C1FlexGrid i_fg)
        {
            Hashtable v_htb = new Hashtable();
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.DIA_CHI, e_col_Number.DIA_CHI);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.DON_GIA_BUOI_HOC, e_col_Number.DON_GIA_BUOI_HOC);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.MA_DOI_TUONG, e_col_Number.MA_DOI_TUONG);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.TONG_SO_BUOI_HOC, e_col_Number.TONG_SO_BUOI_HOC);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.DELETE_YN, e_col_Number.DELETE_YN);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.EMAIL_HS, e_col_Number.EMAIL_HS);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.TEN_LOP_MON, e_col_Number.TEN_LOP_MON);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.TEN, e_col_Number.TEN);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.TONG_TIEN_KHOA_HOC, e_col_Number.TONG_TIEN_KHOA_HOC);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.MA_LOP_MON, e_col_Number.MA_LOP_MON);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.HO_TEN, e_col_Number.HO_TEN);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.TRANG_THAI_LOP_MON, e_col_Number.TRANG_THAI_LOP_MON);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.TEN_LOAI_DOI_TUONG, e_col_Number.TEN_LOAI_DOI_TUONG);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.THOI_GIAN_HOC_TO_DATE, e_col_Number.THOI_GIAN_HOC_TO_DATE);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.THOI_GIAN_HOC_FROM_DATE, e_col_Number.THOI_GIAN_HOC_FROM_DATE);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.ID_LOAI_DOI_TUONG, e_col_Number.ID_LOAI_DOI_TUONG);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.TRANG_THAI_YN, e_col_Number.TRANG_THAI_YN);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.ID_LOP_MON, e_col_Number.ID_LOP_MON);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.TRUONG_DANG_HOC, e_col_Number.TRUONG_DANG_HOC);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.HO, e_col_Number.HO);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.SDT_HS, e_col_Number.SDT_HS);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.NGAY_SINH, e_col_Number.NGAY_SINH);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.ID_GD_HOC, e_col_Number.ID_GD_HOC);
            v_htb.Add(V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.GHI_CHU, e_col_Number.GHI_CHU);

            ITransferDataRow v_obj_trans = new CC1TransferDataRow(i_fg, v_htb, m_ds.V_DM_HOC_SINH_GD_HOC_DM_LOP_MON.NewRow());
            return v_obj_trans;
        }
        private void load_data_2_grid()
        {
            m_ds.Clear();
            m_ds.EnforceConstraints = false;
            string ip_txt_search = m_txt_search.Text;
            //m_ds = new DS_V_DM_HOC_SINH_GD_HOC_DM_LOP_MON();
            m_us.FillDataset(m_ds, "where ID_LOP_MON = " + m_cbo_lop_mon.SelectedValue +
                            " and (MA_DOI_TUONG like '%" + ip_txt_search +
                            "%' or HO_TEN like N'%" + ip_txt_search +
                            "%' or TRUONG_DANG_HOC like N'%" + ip_txt_search +
                            "%' or EMAIL_HS like N'%" + ip_txt_search + "%')");
            //"%' or facebook like n'%" + ip_txt_search + 
            //m_ds = new DS_V_DM_HOC_SINH_GD_HOC_DM_LOP_MON();
            //m_us.FillDataset(m_ds);
            m_fg.Redraw = false;
            CGridUtils.Dataset2C1Grid(m_ds, m_fg, m_obj_trans);

            CGridUtils.MakeSoTT(0, m_fg);
            m_fg.Redraw = true;
        }
        private void grid2us_object(US_V_DM_HOC_SINH_GD_HOC_DM_LOP_MON i_us
            , int i_grid_row)
        {
            DataRow v_dr;
            v_dr = (DataRow)m_fg.Rows[i_grid_row].UserData;
            m_obj_trans.GridRow2DataRow(i_grid_row, v_dr);
            i_us.DataRow2Me(v_dr);
        }
        private void m_cbo_lop_mon_SelectedIndexChanged(object sender, EventArgs e)
        {
            load_data_2_grid();
        }


        private void us_object2grid(US_V_DM_HOC_SINH_GD_HOC_DM_LOP_MON i_us
            , int i_grid_row)
        {
            DataRow v_dr = (DataRow)m_fg.Rows[i_grid_row].UserData;
            i_us.Me2DataRow(v_dr);
            m_obj_trans.DataRow2GridRow(v_dr, i_grid_row);
        }


        private void insert_v_dm_hoc_sinh_gd_hoc_dm_lop_mon()
        {
            //	f250_dm_hs_theo_lop_DE v_fDE = new  f250_dm_hs_theo_lop_DE();								
            //	v_fDE.display();
            //load_data_2_grid();
            try
            {
                F251_dm_hs_theo_lop_de v_fde = new F251_dm_hs_theo_lop_de();
                v_fde.display_4_insert();
                load_data_2_grid();
            }
            catch (Exception v_e)
            {

                throw v_e;
            }


        }

        private void update_v_dm_hoc_sinh_gd_hoc_dm_lop_mon()
        {

            if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
            if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
            grid2us_object(m_us, m_fg.Row);
            //	f250_dm_hs_theo_lop_DE v_fDE = new f250_dm_hs_theo_lop_DE();
            //	v_fDE.display(m_us);
            try
            {
                F251_dm_hs_theo_lop_de v_fde = new F251_dm_hs_theo_lop_de();
                v_fde.display_4_update(m_us);
                load_data_2_grid();
            }
            catch (Exception v_e)
            {

                throw v_e;
            }

        }

        private void delete_v_dm_hoc_sinh_gd_hoc_dm_lop_mon()
        {
            if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
            if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
            //if (BaseMessages.askUser_DataCouldBeDeleted(8) != BaseMessages.IsDataCouldBeDeleted.CouldBeDeleted) return;
            US_V_DM_HOC_SINH_GD_HOC_DM_LOP_MON v_us = new US_V_DM_HOC_SINH_GD_HOC_DM_LOP_MON();
            grid2us_object(v_us, m_fg.Row);
            try
            {

                if (BaseMessages.MsgBox_YES_NO_CANCEL("Bạn có chắc chắn muốn xóa học sinh này không?") == DialogResult.Yes)
                {
                    v_us.Delete_by_Proc(v_us.dcID, v_us.dcID_GD_HOC);
                }
                else
                    return;
                m_fg.Rows.Remove(m_fg.Row);
            }
            catch (Exception v_e)
            {
                v_us.Rollback();
                CDBExceptionHandler v_objErrHandler = new CDBExceptionHandler(v_e,
                    new CDBClientDBExceptionInterpret());
                v_objErrHandler.showErrorMessage();
            }
        }

        private void view_v_dm_hoc_sinh_gd_hoc_dm_lop_mon()
        {
            if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
            if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
            grid2us_object(m_us, m_fg.Row);
            //	f250_dm_hs_theo_lop_DE v_fDE = new f250_dm_hs_theo_lop_DE();			
            //	v_fDE.display(m_us);
        }
        private void set_define_events()
        {
            m_cmd_exit.Click += new EventHandler(m_cmd_exit_Click);
            m_cmd_insert.Click += new EventHandler(m_cmd_insert_Click);
            m_cmd_update.Click += new EventHandler(m_cmd_update_Click);
            m_cmd_delete.Click += new EventHandler(m_cmd_delete_Click);
            m_cmd_view.Click += new EventHandler(m_cmd_view_Click);
            m_cmd_search.Click += m_cmd_search_Click;
        }

        void m_cmd_search_Click(object sender, EventArgs e)
        {
            try
            {
                load_data_2_grid();
            }
            catch (Exception v_e)
            {

                throw v_e;
            }

        }
        #endregion

        //
        //
        //		EVENT HANLDERS
        //
        //
        private void f250_dm_hs_theo_lop_Load(object sender, System.EventArgs e)
        {
            try
            {
                set_initial_form_load();
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }

        }

        private void m_cmd_exit_Click(object sender, EventArgs e)
        {
            try
            {
                this.Close();
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        private void m_cmd_insert_Click(object sender, EventArgs e)
        {
            try
            {
                insert_v_dm_hoc_sinh_gd_hoc_dm_lop_mon();
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        private void m_cmd_update_Click(object sender, EventArgs e)
        {
            try
            {
                update_v_dm_hoc_sinh_gd_hoc_dm_lop_mon();
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        private void m_cmd_delete_Click(object sender, EventArgs e)
        {
            try
            {
                delete_v_dm_hoc_sinh_gd_hoc_dm_lop_mon();
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        private void m_cmd_view_Click(object sender, EventArgs e)
        {
            try
            {
                view_v_dm_hoc_sinh_gd_hoc_dm_lop_mon();
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

    }
}

