///************************************************
/// Generated by: Haihd
/// Date: 15/07/2015 03:53:40
/// Goal: Create Form for V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU
///************************************************


using System;
using System.Data;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

using IP.Core.IPCommon;
using IP.Core.IPException;
using IP.Core.IPData;
using IP.Core.IPUserService;
using IP.Core.IPSystemAdmin;

using BKI_QLTTQuocAnh.US;
using BKI_QLTTQuocAnh.DS;
using BKI_QLTTQuocAnh.DS.CDBNames;

using C1.Win.C1FlexGrid;

namespace BKI_QLTTQuocAnh
{



    public class f361_ban_giao_hoc_phi_giam_tru_theo_lop : System.Windows.Forms.Form
    {
        #region Generate

        internal System.Windows.Forms.ImageList ImageList;
        internal System.Windows.Forms.Panel m_pnl_out_place_dm;
        private C1.Win.C1FlexGrid.C1FlexGrid m_fg;
        internal SIS.Controls.Button.SiSButton m_cmd_delete;
        internal SIS.Controls.Button.SiSButton m_cmd_update;
        internal SIS.Controls.Button.SiSButton m_cmd_insert;
        internal SIS.Controls.Button.SiSButton m_cmd_exit;
        internal SIS.Controls.Button.SiSButton m_cmd_view;
        private Panel panel1;
        internal SIS.Controls.Button.SiSButton m_cmd_search;
        private ComboBox m_cbo_nhan_vien_thu;
        private Label label1;
        private Label m_lbl_den_ngay;
        private DateTimePicker m_dat_den_ngay;
        private DateTimePicker m_dat_tu_ngay;
        private Label m_lbl_tu_ngay;
        private Label m_lbl_header;
        private DevExpress.XtraEditors.SearchLookUpEdit m_sle_lop;
        private DevExpress.XtraGrid.Views.Grid.GridView gridView1;
        private Label label2;
        private DevExpress.XtraGrid.GridControl gridControl;
        private DevExpress.XtraGrid.Views.Grid.GridView gridView;
        private DevExpress.XtraGrid.Columns.GridColumn NGAY_THU;
        private DevExpress.XtraGrid.Columns.GridColumn SO_PHIEU;
        private DevExpress.XtraGrid.Columns.GridColumn NOI_DUNG;
        private DevExpress.XtraGrid.Columns.GridColumn MA_HOC_SINH;
        private DevExpress.XtraGrid.Columns.GridColumn TEN_HOC_VIEN;
        private DevExpress.XtraGrid.Columns.GridColumn NGUOI_THU;
        private DevExpress.XtraEditors.Repository.RepositoryItemTextEdit repositoryItemTextEdit1;
        private DevExpress.XtraGrid.Columns.GridColumn ID;
        private DevExpress.XtraEditors.Repository.RepositoryItemCheckEdit repositoryItemCheckEdit;
        private ComboBox m_cbo_loai_phieu;
        private Label label3;
        private DevExpress.XtraGrid.Columns.GridColumn TIEN_PHAI_THU;
        private DevExpress.XtraGrid.Columns.GridColumn TIEN_GIAM_TRU;
        private DevExpress.XtraGrid.Columns.GridColumn TEN_LOP_MON;
        private DevExpress.XtraGrid.Columns.GridColumn TIEN_THUC_THU;
        private DevExpress.XtraGrid.Columns.GridColumn TEN_LOP;
        private DevExpress.XtraGrid.Columns.GridColumn MA_SO_QUYEN;
        private System.ComponentModel.IContainer components;

        #endregion

        public f361_ban_giao_hoc_phi_giam_tru_theo_lop()
        {
            //
            // Required for Windows Form Designer support
            //
            InitializeComponent();

            //
            // TODO: Add any constructor code after InitializeComponent call
            //
            format_controls();
        }

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code
        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(f361_ban_giao_hoc_phi_giam_tru_theo_lop));
            this.ImageList = new System.Windows.Forms.ImageList(this.components);
            this.m_pnl_out_place_dm = new System.Windows.Forms.Panel();
            this.m_cmd_insert = new SIS.Controls.Button.SiSButton();
            this.m_cmd_update = new SIS.Controls.Button.SiSButton();
            this.m_cmd_view = new SIS.Controls.Button.SiSButton();
            this.m_cmd_delete = new SIS.Controls.Button.SiSButton();
            this.m_cmd_exit = new SIS.Controls.Button.SiSButton();
            this.m_fg = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.panel1 = new System.Windows.Forms.Panel();
            this.m_cbo_loai_phieu = new System.Windows.Forms.ComboBox();
            this.label3 = new System.Windows.Forms.Label();
            this.m_sle_lop = new DevExpress.XtraEditors.SearchLookUpEdit();
            this.gridView1 = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.label2 = new System.Windows.Forms.Label();
            this.m_cmd_search = new SIS.Controls.Button.SiSButton();
            this.m_cbo_nhan_vien_thu = new System.Windows.Forms.ComboBox();
            this.label1 = new System.Windows.Forms.Label();
            this.m_lbl_den_ngay = new System.Windows.Forms.Label();
            this.m_dat_den_ngay = new System.Windows.Forms.DateTimePicker();
            this.m_dat_tu_ngay = new System.Windows.Forms.DateTimePicker();
            this.m_lbl_tu_ngay = new System.Windows.Forms.Label();
            this.m_lbl_header = new System.Windows.Forms.Label();
            this.gridControl = new DevExpress.XtraGrid.GridControl();
            this.gridView = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.TEN_LOP = new DevExpress.XtraGrid.Columns.GridColumn();
            this.NGAY_THU = new DevExpress.XtraGrid.Columns.GridColumn();
            this.SO_PHIEU = new DevExpress.XtraGrid.Columns.GridColumn();
            this.NOI_DUNG = new DevExpress.XtraGrid.Columns.GridColumn();
            this.MA_HOC_SINH = new DevExpress.XtraGrid.Columns.GridColumn();
            this.TEN_HOC_VIEN = new DevExpress.XtraGrid.Columns.GridColumn();
            this.NGUOI_THU = new DevExpress.XtraGrid.Columns.GridColumn();
            this.TIEN_PHAI_THU = new DevExpress.XtraGrid.Columns.GridColumn();
            this.repositoryItemTextEdit1 = new DevExpress.XtraEditors.Repository.RepositoryItemTextEdit();
            this.TIEN_GIAM_TRU = new DevExpress.XtraGrid.Columns.GridColumn();
            this.ID = new DevExpress.XtraGrid.Columns.GridColumn();
            this.repositoryItemCheckEdit = new DevExpress.XtraEditors.Repository.RepositoryItemCheckEdit();
            this.TEN_LOP_MON = new DevExpress.XtraGrid.Columns.GridColumn();
            this.TIEN_THUC_THU = new DevExpress.XtraGrid.Columns.GridColumn();
            this.MA_SO_QUYEN = new DevExpress.XtraGrid.Columns.GridColumn();
            this.m_pnl_out_place_dm.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).BeginInit();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_sle_lop.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridControl)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemTextEdit1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemCheckEdit)).BeginInit();
            this.SuspendLayout();
            // 
            // ImageList
            // 
            this.ImageList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("ImageList.ImageStream")));
            this.ImageList.TransparentColor = System.Drawing.Color.Transparent;
            this.ImageList.Images.SetKeyName(0, "");
            this.ImageList.Images.SetKeyName(1, "");
            this.ImageList.Images.SetKeyName(2, "");
            this.ImageList.Images.SetKeyName(3, "");
            this.ImageList.Images.SetKeyName(4, "");
            this.ImageList.Images.SetKeyName(5, "");
            this.ImageList.Images.SetKeyName(6, "");
            this.ImageList.Images.SetKeyName(7, "");
            this.ImageList.Images.SetKeyName(8, "");
            this.ImageList.Images.SetKeyName(9, "");
            this.ImageList.Images.SetKeyName(10, "");
            this.ImageList.Images.SetKeyName(11, "");
            this.ImageList.Images.SetKeyName(12, "");
            this.ImageList.Images.SetKeyName(13, "");
            this.ImageList.Images.SetKeyName(14, "");
            this.ImageList.Images.SetKeyName(15, "");
            this.ImageList.Images.SetKeyName(16, "");
            this.ImageList.Images.SetKeyName(17, "");
            this.ImageList.Images.SetKeyName(18, "");
            this.ImageList.Images.SetKeyName(19, "");
            this.ImageList.Images.SetKeyName(20, "");
            this.ImageList.Images.SetKeyName(21, "");
            // 
            // m_pnl_out_place_dm
            // 
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_insert);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_update);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_view);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_delete);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_exit);
            this.m_pnl_out_place_dm.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.m_pnl_out_place_dm.Location = new System.Drawing.Point(0, 389);
            this.m_pnl_out_place_dm.Name = "m_pnl_out_place_dm";
            this.m_pnl_out_place_dm.Padding = new System.Windows.Forms.Padding(4);
            this.m_pnl_out_place_dm.Size = new System.Drawing.Size(1247, 84);
            this.m_pnl_out_place_dm.TabIndex = 2;
            // 
            // m_cmd_insert
            // 
            this.m_cmd_insert.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_insert.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_insert.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_insert.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_insert.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_insert.ImageIndex = 13;
            this.m_cmd_insert.ImageList = this.ImageList;
            this.m_cmd_insert.Location = new System.Drawing.Point(92, 4);
            this.m_cmd_insert.Name = "m_cmd_insert";
            this.m_cmd_insert.Size = new System.Drawing.Size(138, 76);
            this.m_cmd_insert.TabIndex = 1;
            this.m_cmd_insert.Text = "&Bàn giao";
            // 
            // m_cmd_update
            // 
            this.m_cmd_update.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_update.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_update.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_update.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_update.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_update.ImageIndex = 3;
            this.m_cmd_update.ImageList = this.ImageList;
            this.m_cmd_update.Location = new System.Drawing.Point(979, 4);
            this.m_cmd_update.Name = "m_cmd_update";
            this.m_cmd_update.Size = new System.Drawing.Size(88, 76);
            this.m_cmd_update.TabIndex = 2;
            this.m_cmd_update.Text = "&Sửa";
            // 
            // m_cmd_view
            // 
            this.m_cmd_view.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_view.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_view.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_view.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_view.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_view.ImageIndex = 18;
            this.m_cmd_view.ImageList = this.ImageList;
            this.m_cmd_view.Location = new System.Drawing.Point(4, 4);
            this.m_cmd_view.Name = "m_cmd_view";
            this.m_cmd_view.Size = new System.Drawing.Size(88, 76);
            this.m_cmd_view.TabIndex = 0;
            this.m_cmd_view.Text = "Xem";
            // 
            // m_cmd_delete
            // 
            this.m_cmd_delete.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_delete.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_delete.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_delete.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_delete.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_delete.ImageIndex = 4;
            this.m_cmd_delete.ImageList = this.ImageList;
            this.m_cmd_delete.Location = new System.Drawing.Point(1067, 4);
            this.m_cmd_delete.Name = "m_cmd_delete";
            this.m_cmd_delete.Size = new System.Drawing.Size(88, 76);
            this.m_cmd_delete.TabIndex = 3;
            this.m_cmd_delete.Text = "&Xoá";
            // 
            // m_cmd_exit
            // 
            this.m_cmd_exit.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_exit.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_exit.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_exit.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_exit.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_exit.ImageIndex = 12;
            this.m_cmd_exit.ImageList = this.ImageList;
            this.m_cmd_exit.Location = new System.Drawing.Point(1155, 4);
            this.m_cmd_exit.Name = "m_cmd_exit";
            this.m_cmd_exit.Size = new System.Drawing.Size(88, 76);
            this.m_cmd_exit.TabIndex = 4;
            this.m_cmd_exit.Text = "Thoát (Esc)";
            // 
            // m_fg
            // 
            this.m_fg.ColumnInfo = resources.GetString("m_fg.ColumnInfo");
            this.m_fg.Location = new System.Drawing.Point(770, 5);
            this.m_fg.Name = "m_fg";
            this.m_fg.Size = new System.Drawing.Size(297, 75);
            this.m_fg.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("m_fg.Styles"));
            this.m_fg.TabIndex = 20;
            this.m_fg.Visible = false;
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.m_cbo_loai_phieu);
            this.panel1.Controls.Add(this.label3);
            this.panel1.Controls.Add(this.m_sle_lop);
            this.panel1.Controls.Add(this.label2);
            this.panel1.Controls.Add(this.m_cmd_search);
            this.panel1.Controls.Add(this.m_fg);
            this.panel1.Controls.Add(this.m_cbo_nhan_vien_thu);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Controls.Add(this.m_lbl_den_ngay);
            this.panel1.Controls.Add(this.m_dat_den_ngay);
            this.panel1.Controls.Add(this.m_dat_tu_ngay);
            this.panel1.Controls.Add(this.m_lbl_tu_ngay);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 44);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1247, 107);
            this.panel1.TabIndex = 0;
            // 
            // m_cbo_loai_phieu
            // 
            this.m_cbo_loai_phieu.FormattingEnabled = true;
            this.m_cbo_loai_phieu.Location = new System.Drawing.Point(87, 69);
            this.m_cbo_loai_phieu.Name = "m_cbo_loai_phieu";
            this.m_cbo_loai_phieu.Size = new System.Drawing.Size(223, 21);
            this.m_cbo_loai_phieu.TabIndex = 9;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(8, 73);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(59, 13);
            this.label3.TabIndex = 8;
            this.label3.Text = "Loại phiếu ";
            // 
            // m_sle_lop
            // 
            this.m_sle_lop.EditValue = "";
            this.m_sle_lop.Location = new System.Drawing.Point(304, 35);
            this.m_sle_lop.Name = "m_sle_lop";
            this.m_sle_lop.Properties.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.Office2003;
            this.m_sle_lop.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.m_sle_lop.Properties.NullText = "Chọn lớp";
            this.m_sle_lop.Properties.View = this.gridView1;
            this.m_sle_lop.Size = new System.Drawing.Size(228, 20);
            this.m_sle_lop.TabIndex = 7;
            // 
            // gridView1
            // 
            this.gridView1.FocusRectStyle = DevExpress.XtraGrid.Views.Grid.DrawFocusRectStyle.RowFocus;
            this.gridView1.Name = "gridView1";
            this.gridView1.OptionsSelection.EnableAppearanceFocusedCell = false;
            this.gridView1.OptionsView.ShowGroupPanel = false;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            this.label2.Location = new System.Drawing.Point(260, 39);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(25, 13);
            this.label2.TabIndex = 6;
            this.label2.Text = "Lớp";
            // 
            // m_cmd_search
            // 
            this.m_cmd_search.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_search.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_search.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_search.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_search.ImageIndex = 5;
            this.m_cmd_search.ImageList = this.ImageList;
            this.m_cmd_search.Location = new System.Drawing.Point(444, 65);
            this.m_cmd_search.Name = "m_cmd_search";
            this.m_cmd_search.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_search.TabIndex = 10;
            this.m_cmd_search.Text = "&Lọc phiếu";
            // 
            // m_cbo_nhan_vien_thu
            // 
            this.m_cbo_nhan_vien_thu.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.m_cbo_nhan_vien_thu.FormattingEnabled = true;
            this.m_cbo_nhan_vien_thu.Location = new System.Drawing.Point(87, 35);
            this.m_cbo_nhan_vien_thu.Name = "m_cbo_nhan_vien_thu";
            this.m_cbo_nhan_vien_thu.Size = new System.Drawing.Size(143, 21);
            this.m_cbo_nhan_vien_thu.TabIndex = 5;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(8, 39);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(56, 13);
            this.label1.TabIndex = 4;
            this.label1.Text = "Nhân viên";
            // 
            // m_lbl_den_ngay
            // 
            this.m_lbl_den_ngay.AutoSize = true;
            this.m_lbl_den_ngay.Location = new System.Drawing.Point(232, 9);
            this.m_lbl_den_ngay.Name = "m_lbl_den_ngay";
            this.m_lbl_den_ngay.Size = new System.Drawing.Size(53, 13);
            this.m_lbl_den_ngay.TabIndex = 2;
            this.m_lbl_den_ngay.Text = "Đến ngày";
            // 
            // m_dat_den_ngay
            // 
            this.m_dat_den_ngay.CustomFormat = "dd/MM/yyyy";
            this.m_dat_den_ngay.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.m_dat_den_ngay.Location = new System.Drawing.Point(304, 5);
            this.m_dat_den_ngay.Name = "m_dat_den_ngay";
            this.m_dat_den_ngay.Size = new System.Drawing.Size(128, 20);
            this.m_dat_den_ngay.TabIndex = 3;
            // 
            // m_dat_tu_ngay
            // 
            this.m_dat_tu_ngay.CustomFormat = "dd/MM/yyyy";
            this.m_dat_tu_ngay.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.m_dat_tu_ngay.Location = new System.Drawing.Point(87, 5);
            this.m_dat_tu_ngay.Name = "m_dat_tu_ngay";
            this.m_dat_tu_ngay.Size = new System.Drawing.Size(121, 20);
            this.m_dat_tu_ngay.TabIndex = 1;
            // 
            // m_lbl_tu_ngay
            // 
            this.m_lbl_tu_ngay.AutoSize = true;
            this.m_lbl_tu_ngay.Location = new System.Drawing.Point(8, 9);
            this.m_lbl_tu_ngay.Name = "m_lbl_tu_ngay";
            this.m_lbl_tu_ngay.Size = new System.Drawing.Size(46, 13);
            this.m_lbl_tu_ngay.TabIndex = 0;
            this.m_lbl_tu_ngay.Text = "Từ ngày";
            // 
            // m_lbl_header
            // 
            this.m_lbl_header.Dock = System.Windows.Forms.DockStyle.Top;
            this.m_lbl_header.Font = new System.Drawing.Font("Microsoft Sans Serif", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.m_lbl_header.ForeColor = System.Drawing.Color.Maroon;
            this.m_lbl_header.Location = new System.Drawing.Point(0, 0);
            this.m_lbl_header.Name = "m_lbl_header";
            this.m_lbl_header.Size = new System.Drawing.Size(1247, 44);
            this.m_lbl_header.TabIndex = 0;
            this.m_lbl_header.Text = "BÀN GIAO TIỀN";
            this.m_lbl_header.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // gridControl
            // 
            this.gridControl.Cursor = System.Windows.Forms.Cursors.Default;
            this.gridControl.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridControl.Location = new System.Drawing.Point(0, 151);
            this.gridControl.MainView = this.gridView;
            this.gridControl.Name = "gridControl";
            this.gridControl.RepositoryItems.AddRange(new DevExpress.XtraEditors.Repository.RepositoryItem[] {
            this.repositoryItemCheckEdit,
            this.repositoryItemTextEdit1});
            this.gridControl.Size = new System.Drawing.Size(1247, 238);
            this.gridControl.TabIndex = 1;
            this.gridControl.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.gridView});
            // 
            // gridView
            // 
            this.gridView.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.Office2003;
            this.gridView.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] {
            this.TEN_LOP,
            this.NGAY_THU,
            this.MA_SO_QUYEN,
            this.SO_PHIEU,
            this.NOI_DUNG,
            this.MA_HOC_SINH,
            this.TEN_HOC_VIEN,
            this.NGUOI_THU,
            this.TIEN_PHAI_THU,
            this.TIEN_GIAM_TRU,
            this.ID});
            this.gridView.GridControl = this.gridControl;
            this.gridView.Name = "gridView";
            this.gridView.OptionsSelection.MultiSelect = true;
            this.gridView.OptionsSelection.MultiSelectMode = DevExpress.XtraGrid.Views.Grid.GridMultiSelectMode.CheckBoxRowSelect;
            this.gridView.OptionsSelection.ShowCheckBoxSelectorInColumnHeader = DevExpress.Utils.DefaultBoolean.True;
            this.gridView.OptionsSelection.ShowCheckBoxSelectorInPrintExport = DevExpress.Utils.DefaultBoolean.True;
            this.gridView.OptionsView.ShowGroupPanel = false;
            // 
            // TEN_LOP
            // 
            this.TEN_LOP.Caption = "Lớp";
            this.TEN_LOP.FieldName = "TEN_LOP_MON";
            this.TEN_LOP.Name = "TEN_LOP";
            this.TEN_LOP.Visible = true;
            this.TEN_LOP.VisibleIndex = 1;
            // 
            // NGAY_THU
            // 
            this.NGAY_THU.Caption = "Ngày thu";
            this.NGAY_THU.FieldName = "NGAY_THU";
            this.NGAY_THU.Name = "NGAY_THU";
            this.NGAY_THU.OptionsColumn.AllowEdit = false;
            this.NGAY_THU.Visible = true;
            this.NGAY_THU.VisibleIndex = 3;
            this.NGAY_THU.Width = 166;
            // 
            // SO_PHIEU
            // 
            this.SO_PHIEU.Caption = "Số phiếu";
            this.SO_PHIEU.FieldName = "SO_PHIEU";
            this.SO_PHIEU.Name = "SO_PHIEU";
            this.SO_PHIEU.OptionsColumn.AllowEdit = false;
            this.SO_PHIEU.Visible = true;
            this.SO_PHIEU.VisibleIndex = 4;
            this.SO_PHIEU.Width = 102;
            // 
            // NOI_DUNG
            // 
            this.NOI_DUNG.Caption = "Nội dung";
            this.NOI_DUNG.FieldName = "NOI_DUNG";
            this.NOI_DUNG.Name = "NOI_DUNG";
            this.NOI_DUNG.OptionsColumn.AllowEdit = false;
            this.NOI_DUNG.Visible = true;
            this.NOI_DUNG.VisibleIndex = 5;
            this.NOI_DUNG.Width = 217;
            // 
            // MA_HOC_SINH
            // 
            this.MA_HOC_SINH.Caption = "Mã HV";
            this.MA_HOC_SINH.FieldName = "MA_HOC_SINH";
            this.MA_HOC_SINH.Name = "MA_HOC_SINH";
            this.MA_HOC_SINH.OptionsColumn.AllowEdit = false;
            this.MA_HOC_SINH.Visible = true;
            this.MA_HOC_SINH.VisibleIndex = 6;
            this.MA_HOC_SINH.Width = 73;
            // 
            // TEN_HOC_VIEN
            // 
            this.TEN_HOC_VIEN.Caption = "Tên HV";
            this.TEN_HOC_VIEN.FieldName = "HO_TEN_HS";
            this.TEN_HOC_VIEN.Name = "TEN_HOC_VIEN";
            this.TEN_HOC_VIEN.OptionsColumn.AllowEdit = false;
            this.TEN_HOC_VIEN.Visible = true;
            this.TEN_HOC_VIEN.VisibleIndex = 7;
            this.TEN_HOC_VIEN.Width = 178;
            // 
            // NGUOI_THU
            // 
            this.NGUOI_THU.Caption = "Người thu";
            this.NGUOI_THU.FieldName = "TEN_NGUOI_THU";
            this.NGUOI_THU.Name = "NGUOI_THU";
            this.NGUOI_THU.OptionsColumn.AllowEdit = false;
            this.NGUOI_THU.Visible = true;
            this.NGUOI_THU.VisibleIndex = 8;
            this.NGUOI_THU.Width = 226;
            // 
            // TIEN_PHAI_THU
            // 
            this.TIEN_PHAI_THU.Caption = "Học phí";
            this.TIEN_PHAI_THU.ColumnEdit = this.repositoryItemTextEdit1;
            this.TIEN_PHAI_THU.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.TIEN_PHAI_THU.FieldName = "TIEN_PHAI_THU";
            this.TIEN_PHAI_THU.Name = "TIEN_PHAI_THU";
            this.TIEN_PHAI_THU.OptionsColumn.AllowEdit = false;
            this.TIEN_PHAI_THU.Visible = true;
            this.TIEN_PHAI_THU.VisibleIndex = 9;
            this.TIEN_PHAI_THU.Width = 150;
            // 
            // repositoryItemTextEdit1
            // 
            this.repositoryItemTextEdit1.AutoHeight = false;
            this.repositoryItemTextEdit1.Mask.EditMask = "n0";
            this.repositoryItemTextEdit1.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.Numeric;
            this.repositoryItemTextEdit1.Mask.UseMaskAsDisplayFormat = true;
            this.repositoryItemTextEdit1.Name = "repositoryItemTextEdit1";
            // 
            // TIEN_GIAM_TRU
            // 
            this.TIEN_GIAM_TRU.Caption = "Giảm trừ";
            this.TIEN_GIAM_TRU.ColumnEdit = this.repositoryItemTextEdit1;
            this.TIEN_GIAM_TRU.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.TIEN_GIAM_TRU.FieldName = "TIEN_GIAM_TRU";
            this.TIEN_GIAM_TRU.Name = "TIEN_GIAM_TRU";
            this.TIEN_GIAM_TRU.OptionsColumn.AllowEdit = false;
            this.TIEN_GIAM_TRU.Visible = true;
            this.TIEN_GIAM_TRU.VisibleIndex = 10;
            this.TIEN_GIAM_TRU.Width = 150;
            // 
            // ID
            // 
            this.ID.Caption = "ID";
            this.ID.FieldName = "ID";
            this.ID.Name = "ID";
            // 
            // repositoryItemCheckEdit
            // 
            this.repositoryItemCheckEdit.AutoHeight = false;
            this.repositoryItemCheckEdit.Caption = "Check";
            this.repositoryItemCheckEdit.Name = "repositoryItemCheckEdit";
            this.repositoryItemCheckEdit.NullStyle = DevExpress.XtraEditors.Controls.StyleIndeterminate.Unchecked;
            // 
            // TEN_LOP_MON
            // 
            this.TEN_LOP_MON.Caption = "Lớp";
            this.TEN_LOP_MON.FieldName = "TEN_LOP_MON";
            this.TEN_LOP_MON.Name = "TEN_LOP_MON";
            this.TEN_LOP_MON.OptionsColumn.AllowEdit = false;
            this.TEN_LOP_MON.OptionsEditForm.Visible = DevExpress.Utils.DefaultBoolean.True;
            this.TEN_LOP_MON.UnboundType = DevExpress.Data.UnboundColumnType.String;
            this.TEN_LOP_MON.Width = 204;
            // 
            // TIEN_THUC_THU
            // 
            this.TIEN_THUC_THU.Caption = "Tiền thực thu";
            this.TIEN_THUC_THU.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
            this.TIEN_THUC_THU.FieldName = "TIEN_THUC_THU";
            this.TIEN_THUC_THU.Name = "TIEN_THUC_THU";
            this.TIEN_THUC_THU.OptionsColumn.AllowEdit = false;
            this.TIEN_THUC_THU.Width = 215;
            // 
            // MA_SO_QUYEN
            // 
            this.MA_SO_QUYEN.Caption = "Quyển số";
            this.MA_SO_QUYEN.FieldName = "MA_SO_QUYEN";
            this.MA_SO_QUYEN.Name = "MA_SO_QUYEN";
            this.MA_SO_QUYEN.Visible = true;
            this.MA_SO_QUYEN.VisibleIndex = 2;
            // 
            // f361_ban_giao_hoc_phi_giam_tru_theo_lop
            // 
            this.AutoScaleBaseSize = new System.Drawing.Size(5, 13);
            this.ClientSize = new System.Drawing.Size(1247, 473);
            this.Controls.Add(this.gridControl);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.m_lbl_header);
            this.Controls.Add(this.m_pnl_out_place_dm);
            this.Name = "f361_ban_giao_hoc_phi_giam_tru_theo_lop";
            this.Text = "F361 - Bàn giao học phí, giảm trừ theo lớp";
            this.Load += new System.EventHandler(this.f361_ban_giao_hoc_phi_giam_tru_theo_lop_Load);
            this.m_pnl_out_place_dm.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).EndInit();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_sle_lop.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridControl)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemTextEdit1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.repositoryItemCheckEdit)).EndInit();
            this.ResumeLayout(false);

        }
        #endregion

        #region Public Interface
        public void display()
        {
            this.ShowDialog();
        }
        #endregion

        #region Data Structure
        private enum e_col_Number
        {
            HO_TEN_PH = 7
,
            SO_PHIEU = 3
                ,
            NGAY_THU = 1
                ,
            TEN_LOAI_PHIEU_THU = 2
                ,
            TIEN_THUC_THU = 11
                ,
            TEN_LOP_MON = 5
                ,
            TIEN_GIAM_TRU = 10
                ,
            MA_HOC_SINH = 6
                ,
            NOI_DUNG = 4
                ,
            TIEN_CON_PHAI_THU = 12
                ,
            TEN_NGUOI_THU = 8
                , TIEN_PHAI_THU = 9

        }
        #endregion

        #region Members
        ITransferDataRow m_obj_trans;
        DS_V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU m_ds = new DS_V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU();
        US_V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU m_us = new US_V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU();
        #endregion

        #region Private Methods
        private void format_controls()
        {
            CControlFormat.setFormStyle(this, new CAppContext_201());
            CControlFormat.setC1FlexFormat(m_fg);
            CGridUtils.AddSave_Excel_Handlers(m_fg);
            CGridUtils.AddSearch_Handlers(m_fg);
            set_define_events();
            this.KeyPreview = true;
        }

        private void set_initial_form_load()
        {
            m_obj_trans = get_trans_object(m_fg);
            load_data_2_cbo_nhan_vien();
            load_data_to_sle_lop();
            load_data_2_cbo_loai_phieu();
            //load_data_2_grid();		
        }

        //private bool check_validate_data_is_ok()
        //{
        //    if (m_sle_lop.EditValue == null || m_sle_lop.Text == "")
        //    {
        //        MessageBox.Show("Bạn phải chọn lớp trước nhé!!!");
        //        return false;
        //    }
        //    return true;
        //}

        private void load_data_2_cbo_loai_phieu()
        {
            CCommon.load_data_2_cbo_loai_phieu_thu(
                CONST_LOAI_TU_DIEN.LOAI_PHIEU_THU,
                m_cbo_loai_phieu);

            BKI_QLTTQuocAnh.DS.DS_CM_DM_TU_DIEN v_ds = new BKI_QLTTQuocAnh.DS.DS_CM_DM_TU_DIEN();
            BKI_QLTTQuocAnh.US.US_CM_DM_TU_DIEN v_us = new BKI_QLTTQuocAnh.US.US_CM_DM_TU_DIEN();
            v_us.FillDataset(v_ds, "where id_loai_tu_dien = " + 5 + "and id in (27,54)");

            //DataRow v_dr = v_ds.CM_DM_TU_DIEN.NewRow();
            //v_dr[CM_DM_TU_DIEN.ID] = -1;
            //v_dr[CM_DM_TU_DIEN.MA_TU_DIEN] = "TAT_CA";
            //v_dr[CM_DM_TU_DIEN.ID_LOAI_TU_DIEN] = -1;
            //v_dr[CM_DM_TU_DIEN.TEN_NGAN] = "--Tất cả--";
            //v_dr[CM_DM_TU_DIEN.TEN] = "--Tất cả--";
            //v_dr[CM_DM_TU_DIEN.GHI_CHU] = "";

            //v_ds.CM_DM_TU_DIEN.Rows.InsertAt(v_dr, 0);

            m_cbo_loai_phieu.DataSource = v_ds.CM_DM_TU_DIEN;
            m_cbo_loai_phieu.DisplayMember = CM_DM_TU_DIEN.TEN_NGAN;
            m_cbo_loai_phieu.ValueMember = CM_DM_TU_DIEN.ID;

            m_cbo_loai_phieu.SelectedIndex = 0;

        }

        private void load_data_2_cbo_nhan_vien()
        {
            DS_V_HT_NGUOI_SU_DUNG v_ds = new DS_V_HT_NGUOI_SU_DUNG();
            US_V_HT_NGUOI_SU_DUNG v_us = new US_V_HT_NGUOI_SU_DUNG();
            v_us.FillDataset(v_ds);
            DataRow v_dr = v_ds.V_HT_NGUOI_SU_DUNG.NewRow();
            v_dr[V_HT_NGUOI_SU_DUNG.ID] = -1;
            v_dr[V_HT_NGUOI_SU_DUNG.TEN_TRUY_CAP] = "All";
            v_dr[V_HT_NGUOI_SU_DUNG.TEN] = "--Tất cả---";
            v_dr[V_HT_NGUOI_SU_DUNG.MAT_KHAU] = 123;
            v_dr[V_HT_NGUOI_SU_DUNG.NGAY_TAO] = "2015-01-20";
            v_dr[V_HT_NGUOI_SU_DUNG.NGUOI_TAO] = "ADMIN";
            v_dr[V_HT_NGUOI_SU_DUNG.TRANG_THAI] = "0";
            v_dr[V_HT_NGUOI_SU_DUNG.BUILT_IN_YN] = "Y";
            v_dr[V_HT_NGUOI_SU_DUNG.ID_USER_GROUP] = 3;
            v_ds.V_HT_NGUOI_SU_DUNG.Rows.InsertAt(v_dr, 0);

            m_cbo_nhan_vien_thu.DataSource = v_ds.V_HT_NGUOI_SU_DUNG;
            m_cbo_nhan_vien_thu.DisplayMember = V_HT_NGUOI_SU_DUNG.TEN;
            m_cbo_nhan_vien_thu.ValueMember = V_HT_NGUOI_SU_DUNG.ID;
            m_cbo_nhan_vien_thu.SelectedIndex = 0;
        }

        private void load_data_to_sle_lop()
        {
            //Chinh hien thi nguoi dung
            m_sle_lop.Properties.DataSource = load_data_2_ds_dm_lop().DM_LOP_MON;
            m_sle_lop.Properties.DisplayMember = DM_LOP_MON.MO_TA;
            m_sle_lop.Properties.ValueMember = DM_LOP_MON.ID;

            m_sle_lop.Properties.PopulateViewColumns();
            m_sle_lop.Properties.View.Columns[DM_LOP_MON.ID].Visible = false;
            m_sle_lop.Properties.View.Columns[DM_LOP_MON.ID_LOP].Visible = false;
            m_sle_lop.Properties.View.Columns[DM_LOP_MON.ID_MON].Visible = false;
            m_sle_lop.Properties.View.Columns[DM_LOP_MON.TRANG_THAI_LOP_MON].Visible = false;
            m_sle_lop.Properties.View.Columns[DM_LOP_MON.DON_GIA_BUOI_HOC].Visible = false;
            m_sle_lop.Properties.View.Columns[DM_LOP_MON.TONG_TIEN_KHOA_HOC].Visible = false;
            m_sle_lop.Properties.View.Columns[DM_LOP_MON.TONG_SO_BUOI_HOC].Visible = false;
            m_sle_lop.Properties.View.Columns[DM_LOP_MON.THOI_GIAN_HOC_TO_DATE].Visible = false;
            m_sle_lop.Properties.View.Columns[DM_LOP_MON.THOI_GIAN_HOC_FROM_DATE].Visible = false;
            m_sle_lop.Properties.View.Columns[DM_LOP_MON.GHI_CHU].Visible = false;
            m_sle_lop.Properties.View.Columns[DM_LOP_MON.ID_TRO_GIANG].Visible = false;

            m_sle_lop.Properties.View.Columns[DM_LOP_MON.MO_TA].Width = 300;
            m_sle_lop.Properties.View.Columns[DM_LOP_MON.MA_LOP_MON].Width = 150;

            m_sle_lop.Properties.View.Columns[DM_LOP_MON.MA_LOP_MON].Caption = "Mã lớp";
            m_sle_lop.Properties.View.Columns[DM_LOP_MON.MO_TA].Caption = "Chọn tên lớp";

            m_sle_lop.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.Standard;
            m_sle_lop.Properties.BestFitMode = DevExpress.XtraEditors.Controls.BestFitMode.BestFit;
        }

        private DS_DM_LOP_MON load_data_2_ds_dm_lop()
        {
            DS_DM_LOP_MON v_ds = new DS_DM_LOP_MON();
            US_DM_LOP_MON v_us = new US_DM_LOP_MON();
            string v_str_filter = "where TRANG_THAI_LOP_MON = " + CONST_TRANG_THAI_LOP_MON.DANG_HOAT_DONG;
            v_ds.Clear();
            v_ds.EnforceConstraints = false;
            v_us.FillDataset(v_ds, v_str_filter);

            return v_ds;
        }

        private ITransferDataRow get_trans_object(C1.Win.C1FlexGrid.C1FlexGrid i_fg)
        {
            Hashtable v_htb = new Hashtable();
            v_htb.Add(V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.HO_TEN_PH, e_col_Number.HO_TEN_PH);
            v_htb.Add(V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.SO_PHIEU, e_col_Number.SO_PHIEU);
            v_htb.Add(V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.NGAY_THU, e_col_Number.NGAY_THU);
            v_htb.Add(V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.TEN_LOAI_PHIEU_THU, e_col_Number.TEN_LOAI_PHIEU_THU);
            v_htb.Add(V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.TIEN_THUC_THU, e_col_Number.TIEN_THUC_THU);
            v_htb.Add(V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.TEN_LOP_MON, e_col_Number.TEN_LOP_MON);
            v_htb.Add(V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.TIEN_GIAM_TRU, e_col_Number.TIEN_GIAM_TRU);
            v_htb.Add(V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.MA_HOC_SINH, e_col_Number.MA_HOC_SINH);
            v_htb.Add(V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.NOI_DUNG, e_col_Number.NOI_DUNG);
            v_htb.Add(V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.TIEN_CON_PHAI_THU, e_col_Number.TIEN_CON_PHAI_THU);
            v_htb.Add(V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.TEN_NGUOI_THU, e_col_Number.TEN_NGUOI_THU);
            v_htb.Add(V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.TIEN_PHAI_THU, e_col_Number.TIEN_PHAI_THU);

            ITransferDataRow v_obj_trans = new CC1TransferDataRow(i_fg, v_htb, m_ds.V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.NewRow());
            return v_obj_trans;
        }

        private void load_data_2_grid()
        {
            //m_ds = new DS_V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU();
            //m_us.FillDataset(m_ds);
            //m_fg.Redraw = false;
            //CGridUtils.Dataset2C1Grid(m_ds, m_fg, m_obj_trans);
            //m_fg.Redraw = true;
            m_ds = new DS_V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU();
            m_ds.Clear();
            m_ds.EnforceConstraints = false;

            if (m_sle_lop.EditValue == null || m_sle_lop.Text == "")
            {
                load_all_data_2_grid();
            }
            else
            {
                load_data_2_grid_by_id_lop();
            }
        }

        private void load_all_data_2_grid()
        {
            if (m_cbo_loai_phieu.SelectedIndex == 0)
            {
                m_us.FillDataset_lay_ds_hoc_phi_theo_lop(
                m_ds
                , m_dat_tu_ngay.Value.Date
                , m_dat_den_ngay.Value.Date
                , CIPConvert.ToDecimal(m_cbo_nhan_vien_thu.SelectedValue)
                ,-1);

                gridControl.DataSource = m_ds.V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU;
                gridView.Columns[V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.TIEN_PHAI_THU].Visible = true;
                gridView.Columns[V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.TIEN_GIAM_TRU].Visible = false;
            }
            else
            {
                m_us.FillDataset_lay_ds_giam_tru_theo_lop(
                m_ds
                , m_dat_tu_ngay.Value.Date
                , m_dat_den_ngay.Value.Date
                , CIPConvert.ToDecimal(m_cbo_nhan_vien_thu.SelectedValue)
                ,-1);

                gridControl.DataSource = m_ds.V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU;
                gridView.Columns[V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.TIEN_GIAM_TRU].Visible = true;
                gridView.Columns[V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.TIEN_PHAI_THU].Visible = false;
            }
        }

        private void load_data_2_grid_by_id_lop()
        {
            if (m_cbo_loai_phieu.SelectedIndex == 0)
            {
                m_us.FillDataset_lay_ds_hoc_phi_theo_lop(
                m_ds
                , m_dat_tu_ngay.Value.Date
                , m_dat_den_ngay.Value.Date
                , CIPConvert.ToDecimal(m_cbo_nhan_vien_thu.SelectedValue)
                , CIPConvert.ToDecimal(m_sle_lop.EditValue));

                gridControl.DataSource = m_ds.V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU;
                gridView.Columns[V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.TIEN_PHAI_THU].Visible = true;
                gridView.Columns[V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.TIEN_GIAM_TRU].Visible = false;
            }
            else
            {
                m_us.FillDataset_lay_ds_giam_tru_theo_lop(
                m_ds
                , m_dat_tu_ngay.Value.Date
                , m_dat_den_ngay.Value.Date
                , CIPConvert.ToDecimal(m_cbo_nhan_vien_thu.SelectedValue)
                , CIPConvert.ToDecimal(m_sle_lop.EditValue));

                gridControl.DataSource = m_ds.V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU;
                gridView.Columns[V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.TIEN_GIAM_TRU].Visible = true;
                gridView.Columns[V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU.TIEN_PHAI_THU].Visible = false;
            }
        }

        private void grid2us_object(US_V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU i_us
            , int i_grid_row)
        {
            DataRow v_dr;
            v_dr = (DataRow)m_fg.Rows[i_grid_row].UserData;
            m_obj_trans.GridRow2DataRow(i_grid_row, v_dr);
            i_us.DataRow2Me(v_dr);
        }


        private void us_object2grid(US_V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU i_us
            , int i_grid_row)
        {
            DataRow v_dr = (DataRow)m_fg.Rows[i_grid_row].UserData;
            i_us.Me2DataRow(v_dr);
            m_obj_trans.DataRow2GridRow(v_dr, i_grid_row);
        }


        private void insert_v_rpt_bao_cao_danh_sach_phieu_thu()
        {
            //	f361_ban_giao_hoc_phi_giam_tru_theo_lop_DE v_fDE = new  f361_ban_giao_hoc_phi_giam_tru_theo_lop_DE();								
            //	v_fDE.display();
            load_data_2_grid();
        }

        private void update_v_rpt_bao_cao_danh_sach_phieu_thu()
        {
            if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
            if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
            grid2us_object(m_us, m_fg.Row);
            //	f361_ban_giao_hoc_phi_giam_tru_theo_lop_DE v_fDE = new f361_ban_giao_hoc_phi_giam_tru_theo_lop_DE();
            //	v_fDE.display(m_us);
            load_data_2_grid();
        }

        private void delete_v_rpt_bao_cao_danh_sach_phieu_thu()
        {
            if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
            if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
            if (BaseMessages.askUser_DataCouldBeDeleted(8) != BaseMessages.IsDataCouldBeDeleted.CouldBeDeleted) return;
            US_V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU v_us = new US_V_RPT_BAO_CAO_DANH_SACH_PHIEU_THU();
            grid2us_object(v_us, m_fg.Row);
            try
            {
                v_us.BeginTransaction();
                v_us.Delete();
                v_us.CommitTransaction();
                m_fg.Rows.Remove(m_fg.Row);
            }
            catch (Exception v_e)
            {
                v_us.Rollback();
                CDBExceptionHandler v_objErrHandler = new CDBExceptionHandler(v_e,
                    new CDBClientDBExceptionInterpret());
                v_objErrHandler.showErrorMessage();
            }
        }

        private void view_v_rpt_bao_cao_danh_sach_phieu_thu()
        {
            if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
            if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
            grid2us_object(m_us, m_fg.Row);
            //	f361_ban_giao_hoc_phi_giam_tru_theo_lop_DE v_fDE = new f361_ban_giao_hoc_phi_giam_tru_theo_lop_DE();			
            //	v_fDE.display(m_us);
        }

        private void cap_nhat_ban_giao()
        {
            US_GD_PHIEU_THU v_us_trans = new US_GD_PHIEU_THU();
            try
            {
                if (gridView.GetSelectedRows().Length == 0)
                {
                    MessageBox.Show("Bạn cần chọn phiếu trước!");
                    return;
                }
                v_us_trans.BeginTransaction();

                foreach (var rowHandle in gridView.GetSelectedRows())
                {
                    DataRow v_dr = gridView.GetDataRow(rowHandle);
                    decimal v_id_pt = CIPConvert.ToDecimal(v_dr["ID"].ToString());
                    US_GD_PHIEU_THU v_us_gd_pt = new US_GD_PHIEU_THU(v_id_pt);
                    v_us_gd_pt.dcID_TRANG_THAI = CONST_ID_TRANG_THAI_BAN_GIAO.DA_BAN_GIAO;
                    v_us_gd_pt.UseTransOfUSObject(v_us_trans);
                    v_us_gd_pt.Update();

                    v_us_gd_pt.ClearAllFields();
                }
                v_us_trans.CommitTransaction();
                load_data_2_grid();
                MessageBox.Show("Đã nhận bàn giao các phiếu đã chọn!");
            }
            catch (Exception v_e)
            {
                if (v_us_trans.is_having_transaction())
                {
                    v_us_trans.Rollback();
                }
                throw v_e;
            }
        }

        #endregion

        //
        //
        //		EVENT HANLDERS
        //
        //
        private void set_define_events()
        {
            m_cmd_exit.Click += new EventHandler(m_cmd_exit_Click);
            m_cmd_insert.Click += new EventHandler(m_cmd_insert_Click);
            m_cmd_update.Click += new EventHandler(m_cmd_update_Click);
            m_cmd_delete.Click += new EventHandler(m_cmd_delete_Click);
            m_cmd_view.Click += new EventHandler(m_cmd_view_Click);
            m_cmd_search.Click += m_cmd_search_Click;
            this.KeyDown += f361_ban_giao_hoc_phi_giam_tru_theo_lop_KeyDown;
        }

        private void f361_ban_giao_hoc_phi_giam_tru_theo_lop_Load(object sender, System.EventArgs e)
        {
            try
            {
                set_initial_form_load();
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        private void m_cmd_exit_Click(object sender, EventArgs e)
        {
            try
            {
                this.Close();
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        private void m_cmd_insert_Click(object sender, EventArgs e)
        {
            try
            {
                cap_nhat_ban_giao();
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        private void m_cmd_update_Click(object sender, EventArgs e)
        {
            try
            {
                update_v_rpt_bao_cao_danh_sach_phieu_thu();
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        private void m_cmd_delete_Click(object sender, EventArgs e)
        {
            try
            {
                delete_v_rpt_bao_cao_danh_sach_phieu_thu();
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        private void m_cmd_view_Click(object sender, EventArgs e)
        {
            try
            {
                view_v_rpt_bao_cao_danh_sach_phieu_thu();
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        void m_cmd_search_Click(object sender, EventArgs e)
        {
            try
            {
                //if (check_validate_data_is_ok())
                //{
                load_data_2_grid();
                //}
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        void f361_ban_giao_hoc_phi_giam_tru_theo_lop_KeyDown(object sender, KeyEventArgs e)
        {
            try
            {
                if (e.KeyCode == Keys.Enter)
                {
                    //if (check_validate_data_is_ok())
                    //{
                        load_data_2_grid();
                    //}
                }

            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }


    }
}

